name: Deploy JobApplication

on:
  push:
    branches:
      - main

jobs:
  streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ› ï¸ Checkout del cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ—ï¸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ğŸš€ Deploy a Streamlit
        uses: streamlit/action@v1
        with:
          email: ${{ secrets.STREAMLIT_EMAIL }}  # Correo asociado a Streamlit
          password: ${{ secrets.STREAMLIT_PASSWORD }}  # ContraseÃ±a (mejor usar API Key)
          repo: "esmerlinp/jobForm"  # Cambia esto con tu usuario y repo en GitHub
          appPath: "main.py"  # Archivo principal de tu app Streamlit
